#!/bin/bash 

# Update system
apt-get update 

# Ensure Apache2 & Git is installed using Puppet
puppet resource package git ensure=present 
puppet resource package apache2 ensure=present 

# Ensure Apache2 service is running using Puppet
puppet resource service apache2 ensure=running 

# Ensure /tmp/4733094m/research is absent and then create as directory
puppet resource file /tmp/4733094m/research ensure=absent force=true
puppet resource file /tmp/4733094m ensure=directory
puppet resource file /tmp/4733094m/research ensure=directory

# Clone the repository
cd /tmp/4733094m/research
git clone -b Prod https://github.com/divya577/4733094m_op_repo.git 

# Replace index.html with the one from the cloned repo (similar to Puppet file resource)
cp -p /tmp/4733094m/research/4733094m_op_repo/4733094m_index.html /var/www/html/index.html
